name: Create Draft Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release
            - Update [pandoc/latex](https://hub.docker.com/r/pandoc/latex) (base image) to ${{ github.ref }}

            Images:
            - `frozenbonito/pandoc-eisvogel-ja:${{ github.ref }}`
            - `frozenbonito/pandoc-eisvogel-ja:${{ github.ref }}-plantuml`
          draft: true
